server:
  port: 7080

spring:
  application:
    name: gateway-service

eureka:
#  instance:
#    prefer-ip-address: false
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

